"""added duration column to songs

Revision ID: 04acc43618b7
Revises: 7add6d99f5a8
Create Date: 2021-03-24 00:25:22.228655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04acc43618b7'
down_revision = '7add6d99f5a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('duration', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'duration')
    # ### end Alembic commands ###
