"""added created_on column to songs

Revision ID: 9b5c7c1042e9
Revises: 2f9b8f527ff9
Create Date: 2021-05-11 20:47:03.062625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b5c7c1042e9'
down_revision = '2f9b8f527ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('uploaded_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'uploaded_date')
    # ### end Alembic commands ###
