"""empty message

Revision ID: 59c81876311e
Revises: 5a5abdd9a797
Create Date: 2021-03-23 06:30:29.094578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c81876311e'
down_revision = '5a5abdd9a797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlists',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('song_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('join_playlist',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('playlist_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'playlist_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('join_playlist')
    op.drop_table('playlists')
    # ### end Alembic commands ###
