"""changed normalized data to a db.TEXT

Revision ID: d55f24ec4fd8
Revises: 04acc43618b7
Create Date: 2021-03-24 00:50:59.150525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd55f24ec4fd8'
down_revision = '04acc43618b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'normalized_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('normalized_data', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
