"""changed normalized data to a db.TEXT

Revision ID: 32be796ecc5b
Revises: d55f24ec4fd8
Create Date: 2021-03-24 00:51:28.987306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32be796ecc5b'
down_revision = 'd55f24ec4fd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('normalized_data', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'normalized_data')
    # ### end Alembic commands ###
